version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=test
      - POSTGRES_DB=test
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - postgres
